### ISSUE TITLE
URLs without http(s):// fail to load

### ISSUE THREAD

**Issue by paulofneves** [embedly/embedly-jquery#45]
Hi there,

I believe the regex used to filter URLs requires that the URL passed includes either http:// or https://

Since embedly supports URLs without the protocol (i.e. http://embed.ly/docs/explore/oembed?url=wikipedia.org), I think this client should also

I changed the regex to
var urlRe = /[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)/;

This now accepts URLs without the protocol, but I am afraid it also lets some bad formatted URLs pass.
What do you think?

**Comment by screeley** [comment]
Right. You'll most likely pass a bunch of bad URLs to Embedly, but if this meets your use case, then use it!
