### ISSUE TITLE
Max res youtube thumbnail url on embedly extract?

### ISSUE THREAD

**Issue by fariasmaiquita** [embedly/embedly-jquery#53]
Hi, little help please. By default when running the embedly extract for a youtube video url the api doesn't return the thumbnail url with the maximum resolution. Is there any option that allows me to change that? I assumed there was but then I looked and looked and found nothing.

**Comment by screeley** [comment]
Hi,

Sorry for the delay, but support@embed.ly is a better place for these general requests. 

For future googlers. 

Embedly respects YouTube's oembed response, which returns 

`https://i.ytimg.com/vi/{id}/hqdefault.jpg` 

You can use a regex to replace `hqdefault.jpg` with `maxresdefault.jpg` to obtain a higher res image, but you are subject to YouTube changing that pattern.
